#!/bin/bash
# android-duplicate-gallery NAME NEW_PACKAGE_NAME SOURCE [install]
cp -r template-gallery3d $2
cd $2
srpl . gallery3d_todo_app_name $1
rm -rf .git*
rm assets/*
# cp ~/babe-example/*.jpg assets/
cp $3/*.jpg assets/
cp $3/icon.png res/drawable/
cd assets/
rename.php
cd ..
manifest.php -n $2
# vim res/values/strings.xml
ant clean
ant debug $4
cp bin/*-debug.apk ~/$2.apk
