#!/bin/bash
# android-duplicate-gallery NEW_PACKAGE_NAME SOURCE [install]
cp -r template-gallery3d $1
cd $1
rm -rf .git*
rm assets/*
# cp ~/babe-example/*.jpg assets/
cp $2/*.jpg assets/
cp $2/icon.png res/drawable/
cd assets/
rename.php
cd ..
manifest.php -n $1
# vim res/values/strings.xml
ant clean
ant debug $3
cp bin/*-debug.apk ~/$1.apk
