#!/bin/bash
# php /home/leo/castfire/extension/toolkit/mp4parse/mp4parse.php $1 $2 $3 $4 $5 $6 $7 $8 $9
php /Users/leo/prj/castfire/svn.castfire.net/origin.castfire.com/inc/extension/toolkit/mp4parse/mp4parse.php $1 $2 $3 $4 $5 $6 $7 $8 $9
